### PR TITLE
Handlers loaded from appcode

### PR DESCRIPTION
**Pull request by erichards97**

### CODE REVIEW

**Comment by erichards97** [comment]
I think this also represents a semantic change ( / bugfix) to the config _.proc.loadhandlers_
Previously _.proc.loadhandlers_ only controlled whether code was/was not loaded from KDBSERVCODE, meaning handler code was always loaded from KDBCODE regardless of the config value.

Given the comment attached to this config in default.q, I figured this behaviour was incorrect:
_// whether to load the message handler code defined at ${KDBCODE}/handlers_

So now _.proc.loadhandlers_ determines whether handlers are loaded at all.

**Review by jonnypress — CHANGES_REQUESTED** [review]
Thanks for the change @erichards97 ! Agree on the comment r.e. bugfix
I think we need to change this to not create the x variable e.g. 
`if[.proc.loadhandlers; .proc.loaddir each {x where not ~[""; ] each x} getenv each `KDBCODE`KDBSERVCODE`KDBAPPCODE),\: "/handlers"];`

**Comment by erichards97** [comment]
Thanks - have updated

**Comment by erichards97** [comment]
Thanks - tested and applied

**Review by jonathonmcmurray — APPROVED** [review]
Looks good, thanks @erichards97 !

**Pull request merged**
